2025-07-11 22:07:38,833 INFO    MainThread:3293125 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-07-11 22:07:38,833 INFO    MainThread:3293125 [wandb_setup.py:_flush():68] Configure stats pid to 3293125
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_setup.py:_flush():68] Loading settings from /home/mingzhi/.config/wandb/settings
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_setup.py:_flush():68] Loading settings from /nvme2/mingzhi/NucCorr/complete_model/wandb/settings
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /nvme2/mingzhi/NucCorr/complete_model/wandb/offline-run-20250711_220738-5rqgt57y/logs/debug.log
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /nvme2/mingzhi/NucCorr/complete_model/wandb/offline-run-20250711_220738-5rqgt57y/logs/debug-internal.log
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_init.py:init():852] calling init triggers
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'data_dir': '/nvme2/mingzhi/NucCorr/NucCorrData/normal_nuclei/normal_nuclei', 'train_file': '/nvme2/mingzhi/NucCorr/NucCorrData/normal_nuclei/normal_nuclei/normal_nuclei_train.txt', 'val_file': '/nvme2/mingzhi/NucCorr/NucCorrData/normal_nuclei/normal_nuclei/normal_nuclei_val.txt', 'batch_size': 16, 'num_workers': 12, 'lr': 0.001, 'weight_decay': 0.0001, 'epochs': 100, 'project_name': 'nuc_corr', 'wandb_key': 'c414fdb4c81a8cd049cb5889fc118e1bfae04b66', 'seed': 618, 'patience': 10, 'min_delta': 0.0001, 'gmm_model_path': '/nvme2/mingzhi/NucCorr/NucDet/gmm_zernike_model.pkl', 'lambda_gmm': 0.01, 'max_zernike_order': 20, '_wandb': {}}
2025-07-11 22:07:38,834 INFO    MainThread:3293125 [wandb_init.py:init():893] starting backend
2025-07-11 22:07:39,246 INFO    MainThread:3293125 [wandb_init.py:init():897] sending inform_init request
2025-07-11 22:07:39,251 INFO    MainThread:3293125 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-11 22:07:39,251 INFO    MainThread:3293125 [wandb_init.py:init():907] backend started and connected
2025-07-11 22:07:39,255 INFO    MainThread:3293125 [wandb_init.py:init():1002] updated telemetry
2025-07-11 22:07:39,256 INFO    MainThread:3293125 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-07-11 22:07:39,495 INFO    MainThread:3293125 [wandb_init.py:init():1101] starting run threads in backend
2025-07-11 22:07:39,706 INFO    MainThread:3293125 [wandb_run.py:_console_start():2566] atexit reg
2025-07-11 22:07:39,706 INFO    MainThread:3293125 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-07-11 22:07:39,706 INFO    MainThread:3293125 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-07-11 22:07:39,706 INFO    MainThread:3293125 [wandb_run.py:_redirect():2506] Redirects installed.
2025-07-11 22:07:39,709 INFO    MainThread:3293125 [wandb_init.py:init():1147] run started, returning control to user process
2025-07-11 22:08:40,567 INFO    MsgRouterThr:3293125 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
2025-07-11 22:08:40,701 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,704 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,705 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,705 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,705 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,706 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,706 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,706 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,706 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,707 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,707 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,707 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,707 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,708 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,708 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,708 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,708 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,709 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,709 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,709 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,709 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,710 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,710 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-11 22:08:40,710 ERROR   MainThread:3293125 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2493, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mingzhi/.conda/envs/pointllm/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
